import { useRef } from 'react';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';

const DynamicBundledEditor = dynamic(() => import('./BundledEditor'), {
	ssr: false,
});

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	const editorRef = useRef<any>(null);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={`${styles.main} ${inter.className}`}>
				<div className={styles.description}>
					<p>
						Get started by editing&nbsp;
						<code className={styles.code}>src/pages/index.tsx</code>
					</p>
					<DynamicBundledEditor
						onInit={(evt: any, editor: any) => (editorRef.current = editor)}
						initialValue=""
						init={{
							height: 500,
							menubar: false,
							plugins: [
								'advlist',
								'anchor',
								'autolink',
								'help',
								'image',
								'link',
								'lists',
								'searchreplace',
								'table',
								'wordcount',
								'fullscreen',
							],
							toolbar:
								'blocks | ' +
								'bold italic forecolor | alignleft aligncenter ' +
								'alignright alignjustify | bullist numlist outdent indent | ' +
								'image | fullscreen',
							content_style:
								'body { font-family:Helvetica,Arial,sans-serif; font-size:14px; background-color: #222f3e; color: #fff; line-height: 1.4; margin: 1rem;}',
							language: 'zh_TW',
							automatic_uploads: true,
							file_picker_types: 'image',
							images_upload_url: '/api/ipfs-uploader?type=img&mode=tinymce',
							skin: 'oxide-dark',
							content_css: 'dark',
						}}
					/>
				</div>
			</main>
		</>
	);
}
